Oneirocom/Magick

apps/client/src/workspaces/spells/windows/AvatarWindow/Avatar.tsx
apps/client/src/workspaces/spells/windows/PlaytestWindow.tsx
apps/server/src/routes/entities.ts

- Fixes being unable to delete events from the database. Prisma expects a number for the id but it was getting a string
- Fix an empty `for` attribute on a label causing console spam whenever you moused over the playtest input field
- Replace hex color string with a hex literal

Event deletion fix + silence a couple of warnings

---

apps/client/src/components/MenuBar/MenuBar.tsx
apps/client/src/screens/HomeScreen/components/FileInput.jsx
apps/client/src/screens/HomeScreen/screens/AllProjects.jsx

Addresses #6. A lot of the actual functionality is tied up inside functional React components so I've opted to simply condense going to the all-projects page and clicking import into a single action.

Add import shortcut to File menu

---

apps/client/src/screens/HomeScreen/screens/CreateNew.tsx

When creating a new spell send a hash of graph nodes, this is required for API validation

fix(feathers-api): ui send hash of spell graph nodes

---

packages/editor/src/components/Select/Select.tsx

There was an issue with the z-index of one of the Inspect Window's inspect elements. 
It was causing it to draw on top of top File dropdown, blocking the Save button.
Before: 
After:

Fixed Z-Index of Inspect Window's select elements 

---

packages/engine/src/lib/nodes/index.ts
packages/engine/src/lib/nodes/strings/PromptTemplate.ts

This node adds a prompt template, which works the same as the generator node but doesn't include any openai stuff

Feature: Add Prompt template node

---

packages/engine/src/lib/nodes/ml/Generator.ts

incorrect spelling of 'davinci' causes error when using this model

fix spelling of 'davinvci' for model name field

---

packages/editor/src/editor.ts
packages/engine/src/lib/plugins/multiCopyPlugin/index.ts
packages/engine/src/lib/plugins/selectionPlugin/index.ts

I add some changes to:
- SelectionPlugin (the dragging blue box)
- MultiCopyPlugin (now you can select any nodes without accumulation check)

make selectionPlugin compatible with multiCopyPlugin

---

Procfile

This small PR allows the Agent server to be created as a background worker. The update to the Procfile doesn't immediately start the worker, but should unlock some new UI in Heroku.

fix: update procfile to include agent worker

---

package.json

Heroku isn't building both the Agent and the Server because of the logic in the `build-server.js` script. This PR is a test to see if bypassing this script will achieve our desired results.

fix: agent worker

---

package.json
packages/editor/src/workspaces/agents/AgentManagerWindow.tsx

This PR includes the `Authorization` header (when required) for calls to the `/agents` endpoint.
It also includes #462 which was needed to get the `AgentManagerWindow` component working.

fix: use auth token when requesting agents

---

packages/editor/src/workspaces/agents/AgentWindow/AgentDetails.tsx

Small bug fix that removes a `JSON.parse` operator on an existing Object. The `selectedAgentData` being passed to `AgentDetails` contains a `rootSpell` property that is already an object, not a string like the `blicVariables` or `secrets` properties. This was causing an `Uncaught SyntaxError: "[object Object]" is not valid JSON` error and preventing the `AgentDetails` component from loading.

fix: invalid json parse on rootSpell

---

packages/server-core/src/sockets/sockets.ts

This small change should resolve the inconsistent `unhandledRejection TypeError: Cannot read properties of undefined (reading 'split') ` error we've been seeing.

fix: check for auth header before extracting value

---

packages/editor/src/windows/agents/AgentManagerWindow.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/windows/agents/AgentWindow/index.tsx
packages/plugin-rest/server/src/services/api/api.class.ts
packages/server-core/src/agents/Agent.ts
packages/server-core/src/services/agents/agents.schema.ts

This PR makes the necessary updates to convert the `rootSpell` property of an `agent` to be handled as a JSON object instead of a string.
Tested locally both with SQLite and Postgres.

feat: convert root spell to JSON

---

packages/editor/src/contexts/EditorProvider.tsx
packages/editor/src/editor.ts
packages/engine/src/lib/plugins/socketPlugin/index.ts
packages/engine/src/lib/spellManager/SpellRunner.ts
packages/engine/src/lib/types.ts

Should work now.  Brought up issue though that "getCurrentSpell" may not be a super reliable way to fetch the current spell. We may want to look into swapping it out in other places.  
The current spell is not injected on every run directly onto the whole context, rather than going through a helper function of the magick interface,

Switch away from getCurrentSpell for socket events

---

apps/server/migrations/20230329030820_agent_string_to_text.ts
apps/server/migrations/20230329031531_documents_string_to_text.ts
apps/server/migrations/20230329031659_events_string_to_text.ts
apps/server/migrations/20230329031824_request_string_to_text.ts
apps/server/migrations/20230329032028_spells_string_to_text.ts

This issue resolves the "character too long for varchar" issue seen when either the request or response to an Agent is too long. Additionally, it also standardizes the use of `text` as opposed to `varchar` column types across all tables.

fix: alter tables to remove string and use text

---

packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
plugins/discord/client/src/components/utils.tsx
plugins/discord/server/src/connectors/discord.ts
plugins/rest/client/src/components/utils.tsx

This PR fixes the agent window (which had a small update regression) and handles cases where the discord token is wrong. The Discord agent will not start if the token is wrong, and the backend doesn't crash.

Handle invalid discord token

---

.env
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
plugins/search/client/src/index.ts
plugins/search/server/src/index.ts
plugins/search/server/src/services/google-search/google-search.ts
plugins/search/shared/src/index.ts

This PR fixes some errors I was facing when trying to build the Editor from scratch. They are all centered around the Google Search plugin.
Not going to lie though; I have no idea how to test these to make sure I didn't just break the plugin. The build errors are gone, but I'm not sure if I actually fixed things or made it worse.
My main concern are with:
```
// plugins/search/server/src/index.ts
...
nodes: Nodes()
...
```
and
```
//plugins/search/shared/src/index.ts
...
return [new SearchGoogle()]
...
```

fix: type errors

---

packages/core/shared/src/nodes/io/Input.ts

This fixes the connection breaking. When switching input type, the trigger no longer breaks the node, in fact it is maintained when switching types.

Fix trigger input breaking input on switch

---

build_notes.md

The current build instructions are:
```
npm install --global nx
npm install --global knex
git clone https://github.com/Oneirocom/Magick magick -b development
cd magick
npm install
npm run dev
```
Remove the old build instructions.

Remove old build instructions.

---

packages/editor/src/windows/DebugConsole/index.tsx

When expanding a node in the console, it was scrolling immediately to bottom of the console

Fix scrolling immediately to bottom of the console when expanding a node in the console

---

apps/client/src/main.tsx

I was troubleshooting posthog as I thought it was not working. Turns out I has adblock on! lol
This is a quick improvement i made while troubleshooting that, it switches to using the PosthogProvider component so that we can integrate things missed as metioned by @Knar33 here https://github.com/Oneirocom/Magick/pull/704#pullrequestreview-1400354771 easier.
setup your envs
```
VITE_APP_POSTHOG_ENABLED=false
VITE_APP_POSTHOG_API_KEY=key
```
and then login to posthog to check for events/recordings.

Switch to the React PostHogProvider

---

packages/core/client/src/components/Drawer/index.tsx
packages/core/shared/src/config.ts
packages/editor/src/screens/HomeScreen/HomeScreen.tsx

- Added a chevron to indicate side drawer minimization
- Added link to the side drawer to open cloud projects in a new tab when clicked
- Delete spell remove it from the tab
- Open the side drawer and close it by clicking the arrow icon
- click on the projects menu in the side drawer
- Delete spell
Refer to the attached video

Fixed deleting spell

---

packages/core/client/src/components/Select/index.tsx

Added `overflow: clip` to dropdowns. See attached screenshots
Before
After

Adds overflow property to dropdown text

---

packages/core/shared/src/nodes/text/TextVariable.ts
packages/core/shared/src/types.ts
plugins/openai/server/src/functions/makeChatCompletion.ts

Should resolve #735 
The system message is now always the last message in a conversation list sent to openai. 
This seems to prevent gpt from forgetting our directive and doesn't seem to affect the output at all (other than making it more strictly following the directive)
In the current development branch
Create a new discord bot spell.
Have a small conversation with it about AI.
I asked it to add some numbers then asked it how to explain AI to my boss.
Observe that after a few messages it seems to forget that its supposed to be a towel.
In my branch
follow the same steps and observe that it never forgets that its a towel.

fix gpt forgetting directive

---

apps/agent/project.json

both agent and server were running their inspectors on port 7778, now server is on 7778 and agent is on 7779
check that both inspector servers are running on their correct parts.

change inspector ports so that server and agent don't clash anymore

---

package-lock.json
package.json

Building on Windows was not working because the dev script was only setting NX_NON_NATIVE_HASHER=true for mac/linux. I fixed this by using cross-env. Also added a nx-win32 as a optional dependency to fix another error.
Build and run Magick.
n/a

Fix windows build

---

packages/editor/src/contexts/LayoutProvider.tsx

Rendering editor layout for active tab only
Open multiple spells 

fixed multiple layout when more than on spell tabs are opened

---

packages/core/shared/src/functions/expandVector.ts
packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
plugins/googleai/server/src/functions/makeChatCompletion.ts

Google AI embeddings are 768 dimensions, but OpenAI embeddings are double that. For now we are spreading the 768 with interpolation, which should have the best result, although ideally we've have a more flexible way to store the embeddings.

Fix n-dimensional Embeddings

---

packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/spells/spells.schema.ts

added 'id' to the create spell schema and removed the spell id delete line

allows spellIds to be preserved on project import

---

packages/core/server/src/services/documents/documents.class.ts
packages/core/server/src/services/events/events.class.ts
packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/requests/requests.class.ts
packages/core/server/src/services/spells/spells.class.ts
packages/core/server/src/services/spells/spells.schema.ts
packages/core/server/src/services/spells/spells.ts

Spells, documents, requests and events fetching has been increased to a limit of 1000.
Make sure all four of those still work, and try to see if the limit goes beyond 100 now.
Pagination soon to follow in another issue.

Increase feathers limits to 1000

---

package.json

Fixes heroku builds. The nx cli is still nrwl, not nx

fixed package name in heroku build pipeline

---

apps/client/src/main.tsx
apps/docs/docs/api/index.md
apps/server/src/index.ts
packages/core/shared/src/agents/AgentManager.ts

Added initLogger calls to each app and lowered the log level of agent manager update logs
ensure that people using npm run dev don't get spammed with update agent logs and that server, agent, and client start without logger related errors
Should resolve some of the spam mentioned in #939

Added initLoggers to the server and client, and lowered the log level on noisy logs

---

packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/spells/spells.ts
packages/editor/src/components/ProjectRow.tsx
packages/editor/src/screens/HomeScreen/AllProjects.tsx

Currently in development, importing projects with subspells (spell node) leads to broken references.
This PR remaps the UUIDs to new UUIDs on import so that they work properly. Also fixes the Duplicate name handling. Spells will now just have the same name. In the future we might want to add part of the UUID in a light color to indicate different same-named spells, but for now this is clean and the least painful.

Fix subspells when importing project

---

packages/agents/src/lib/AgentManager.ts

We now check if oldAgent exists before running the remove handlers.
Make 2 agents, start both, then disable one of them, observe that the worker doesn't crash.
Loopmanager.removeAgent is getting a null agent in our dev environment and crashes the workers, this should stop that.

Stops calling removeHandlers for null oldAgents

---

apps/client/src/main.tsx
apps/docs/docs/api/index.md
packages/core/client/src/providers/ConfigProvider.tsx

This adds posthogEnabled in the AppConfig type. This is used for passing a token from Cloud -> AIDE which we handle in main.tsx.
This is so that we can avoid having two cookie consent popups in each app and just have one in the cloud.
You can test this now. Clone cloud-dev and when you arrive you should be greeted with a cookie popup. Accepting/declining this will set the cookie status for the aide as well.
N/A

Two posthogs, one popup

---

packages/core/server/src/services/documents/documents.ts
packages/core/server/src/services/events/events.ts

Right now embedding searches are limited to a single returned document, but there are many cases where this isn't what we want. This just comments out the hard limit.

Remove query limit hardcode

---

apps/agent/src/index.ts

Pino loggers can't be called implicitly (because it uses some magic)
Some errors were bubbling up in dev and we were getting crashes trying to call pino in this way
run server locally without redis being online
observe a TON of ERRCONNREFUSED errors, but the agent doesn't crash instantly

Pino logger.error can't be called implicitly

---

packages/editor/src/screens/HomeScreen/AllProjects.tsx
packages/editor/src/screens/HomeScreen/HomeScreen.tsx

I made few changes on the onDelete function which handles spell delete , I first made sure that I close the spell before deleting it and I also made changes on the back button which is on open project form and I made sure that we don't use the browser history to navigate back , insead i navigate the user back to `/magic` page
- Create a spell
- Have that spell as your currently active spell tab in the spell editor
- Delete the spell (via the Open spell dialog)
- Confirm the deletion
- check if  the spell is still open in your editor

Fixing deleting a spell while the spell is open and active

---

packages/core/shared/src/nodes/text/ComplexStringMatcher.ts

String matcher was changed and not tested for both conditions, so it's currently broken, this reverts the conditional to fix it.

Fix string matcher

---

packages/core/server/src/services/documents/documents.class.ts

Change asc to desc to fix the document search, currently it's sorted by opposite of what we want, this fixes that!

change asc to desc for document order

---

packages/core/client/src/components/Drawer/ProjectWindow/index.tsx
packages/core/server/src/services/agents/agents.class.ts
packages/core/server/src/services/documents/documents.class.ts
packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/spells/spells.class.ts
packages/editor/src/editor.ts
packages/editor/src/plugins/areaPlugin/restrictor.js

This introduces a "zoom lerp factor" which slows down zoom by 1/4th. This is a temporary fix for an impossible zoom experience on Macbooks.
- Macbook only, so someone with a Mac will need to test. Shouldn't do anything on a PC.
- There is a little glitch at the beginning. To fix this, we would need to update the Oneirocom rete.js fork and handle this zoom internally, seems to be fixed?
- Ideally could control zoom sensitivity from UI, but this sets it on constructor.
- Ideally isn't in the zoom restrictor, although that nicely handles the background etc as well for now.

Slow down zoom in/out

---

packages/core/server/src/services/events/events.class.ts

Currently event recall is returning all events across all channels for any given type.
This PR cleans up the feathers find() call so that it handles both cases with and without embeddings well. These could be further consolidated in a later PR, for now this makes events work and not bleed across channels.

Fix event recall

---

packages/core/server/src/customEmbeddings.ts
packages/core/server/src/services/documents/documents.class.ts
packages/core/server/src/services/documents/documents.ts
packages/core/server/src/vectordb.ts

Now awaits on embedding creation before returning from the create document endpoint
Create a document, observe that everything works normally
this should resolve some weirdness when creating documents, since before the endpoint could return before the embedding creation promise resolved

cleans up doc flow a bit.  awaits on embedding creation

---

packages/editor/src/screens/agents/AgentWindow/AgentPubVariables.tsx

I have the variable name styling and made sure that no matter how long they can be , that they don't overlap into the input area
- Create a spell 
- add text variable node 
- rename that text variable node to eg: AgentPersonality  
- mark that variable as Public
- navigate to Agent settings tab
- set your Root spell to the one you created 
You will see the public variable displayed

Fixing Public variable's name overlaps

---

packages/editor/src/components/MenuBar/menuBar.module.css

I changed the top value of the menu_bar so that we don't lose the hover event when we move down to the menu_panel 
Move to the IDE and try to hover over the top menu items

Fixing drop-down menus  

---

packages/editor/src/windows/TextEditorWindow/index.tsx

On the frontend Monaco editor, the problem is that the code block only updates using _Python_ and _Javascript_ nodes (from **Code** category). This change allows the code block to update for other categories.

Allow text-editor to save code

---

packages/core/shared/src/nodes/io/Input.ts

This PR fixes the input switching so that connections are maintained when the socket type is changed, as long as the key stays the same. Seems to work when switching between output types.

Fix input switching

---

packages/core/server/src/app.ts

Right now the default form limit size is like, 5mb or 8mb or something. This updates it to 50mb which enables the importing of bigger projects.

Enable larger file uploads for larger projects

---

packages/editor/src/screens/EventWindow/EventTable.tsx

I added initial state on useTabel hook with contains pageIndex attribute which will help us to make sure that if we refresh our page after deleting items , that same page will be returned back , instead of loading the first page which causes items reorder 
1. Add many events on events table
2. go to any page other than the first one 
3. try deleting any item 
[Screencast from 23.06.2023 16:15:36.webm](https://github.com/Oneirocom/Magick/assets/55635977/bd5debdd-3232-45bf-a00a-6eebe72b6a92)

fixing page autochange on events pages

---

apps/server/migrations/20230626020445_add-agent-image.ts
packages/core/server/src/services/agents/agents.schema.ts
packages/core/shared/src/schemas.ts

add migrations and feathers schema types for image in the agent
run migrate and see that the column is in the db

add image col to agents table

---

packages/core/shared/src/nodes/events/EventDestructure.ts

This PR adds the connector field to the event destructure output. The socket was there, but it was undefined.

Add connector to event destructure

---

packages/editor/src/screens/EventWindow/event.ts

This lets us see the channelType value in the event window, since it was not exposed before.

Add channel types to event window

---

packages/core/shared/src/plugins/keyCodePlugin/index.ts

For some reason, when I press Delete on a node it breaks my graph badly. However, when I delete a node from the context menu (right click) it is totally fine. This PR throws a warning and fixes this annoyance until we can dig into why exactly nodes break when called that way.
Maybe it's a plugin order issue? :-/

Hot patch: Disable delete key since it breaks graphs

---

packages/core/client/src/components/Drawer/ProjectWindow/index.tsx

This PR adds some checks to remove secrets and API keys from exported agents, so users can share them without handing keys around.

Scrub exported agent

---

apps/docs/docs/nodes/document/GetDocuments.md
packages/core/shared/src/types.ts

We are universally going with distance over similarity now. There is slight difference in the algorithm, but for normalized vectors (which most embeddings are) the distance and similarity are the same, and you can compute similarity as 1 - distance.
This simply changes the documentation and adds distance to the Document type.

Add document distance to type and fix documentation

---

.env
package.json
packages/config/src/config.ts
packages/plugins/openai/server/src/functions/makeChatCompletion.ts
packages/plugins/openai/server/src/functions/makeTextCompletion.ts
packages/plugins/openai/server/src/functions/makeTextEmbedding.ts
packages/plugins/openai/shared/src/index.ts

When DEFAULT_OPENAI_KEY are both set, agents should work without needed to specify an open AI key in agent details, but when there is an open ai key in agent details, then the one provided is used (even if it's not valid)
When PRODUCTION is not set, nothing should change

agents in prod default to our prod openai key but still supports users adding their own key

---

packages/editor/src/screens/DocumentWindow/DocumentTable.tsx
packages/editor/src/screens/EventWindow/EventTable.tsx
packages/editor/src/screens/EventWindow/event.ts
packages/editor/src/screens/RequestWindow/RequestTable.tsx

I added the initial state on useTable hook with contains pageIndex attribute which will help us to make sure that if we refresh our page after deleting items, that same page will be returned back, instead of loading the first page which causes items to reorder
1. Add many requests/documents on request or document table
2. Go to any page other than the first one
3. Try to delete any item
[Screencast from 26.06.2023 17:57:42.webm](https://github.com/Oneirocom/Magick/assets/55635977/9e5733d5-0d70-403a-8d03-232bdddef336)

Fixing page auto-change on documents and requests windows

---

packages/editor/src/components/Node/Node.module.css
packages/editor/src/components/Node/Node.tsx

I fixed the default node name so that it won't ever overlap the node when it's set to a long text
1. Create an input node
2. change the default name of that node and set it to a long text

Fixing node name extending beyond the node

---

packages/core/shared/src/engine.ts

Renames the type to be more appropriate, also should have been Magick instead of Magic :)

Rename MagicComponentCategory to NodeCategory

---

packages/core/server/src/services/documents/documents.ts
packages/core/server/src/services/events/events.ts

Re-add the limit and fix it, this is only for getting the cached embedding so we only need the first one

Get Embedding should only get one (limit 1), not from documents

---

packages/core/server/src/api/apis.ts

node-fetch is no longer necessary, and we want to use the native fetch, not the package

remove node-fetch call

---

package.json
packages/plugins/openai/server/src/functions/makeTextCompletion.ts
packages/plugins/openai/shared/src/index.ts

- The OpenAI chat completion node was calling the wrong model name (gpt4 instead of gpt-4). It now uses the correct model name.
- The logic for getting the OpenAI chat completion API key is corrected, these models no longer throw a 401
- Added a NPM script to build without nx cach called "dev-nocache"

Fix chat/text completion

---

packages/core/client/src/components/Drawer/index.tsx
packages/core/shared/src/plugin.ts
packages/plugins/avatar/client/src/index.ts
packages/plugins/task/client/src/index.ts

- I have added the descriptive tooltip text for the Tasks and Avatar navbar left menu
- Hover on the Tasks and Avatar menu to see the changes

Add descriptive tooltip text on the tasks and avatar left nav button left

---

packages/editor/src/components/Node/Node.tsx

Implemented this approach:
`We may also want to consider having the tooltip occur when hovering over the name of the socket rather than the connection itself.`
I have changed the tooltip occur when hovering over the  connection itself to be on the name of the socket.
- Navigate to the `tooltip_socket_modify` and hover on the input and output name to see the changes
https://github.com/Oneirocom/Magick/assets/55635977/78cdcdac-0d20-4759-b155-f201e8294879

Modify the tooltip text position for the socket input and output

---

packages/core/shared/src/schemas.ts

This fixes some agent creation issues

makes rootSpellId optional on agent creation

---

packages/cloud-agent-manager/src/lib/CloudAgentManager.ts
packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts

Changed the log level of heartbeats to "trace"
Agent startup messages on server cold start now contain timestamps. This ensures that we won't drop jobs if a job id matches a previous one.
Enable an agent then restart the server
Observe that the agent started
IMPORTANT: This will always work the first time, it's important to check a 2nd time so...
restart the server again and observe that the same enabled agent started up again.

Quiets logs and fixes agent startup on server cold start

---

packages/editor/src/windows/TextEditorWindow/index.tsx

I added` debounce` function from the `lodash`  which is working with `useEffect` and it helps us to save data anytime something changes and it's done after 1 secs 
1. Add  Text Variable
2. Navigate to text-editor window 
3. type in any text 
4. refresh the page or visit a different node come back end see it the text is still there 
Fixes: https://github.com/Oneirocom/Magick/issues/1210
[Screencast from 09.08.2023 14:26:38.webm](https://github.com/Oneirocom/Magick/assets/55635977/0b15c681-8e32-48ce-b31a-12f66c1cd5f4)

Adding Auto-save in Text Editor 

---

Procfile

Heroku wants the service recieving HTTP traffic to be named "web" instead of "server"
This just changes that.
https://devcenter.heroku.com/articles/procfile#the-release-process-type

changes server proc name to web as per heroku's requirements

---

docker-compose.yml

Changed docker file to add a network for the cloud db and aide db to communicate for local development
docker network create magick-network
docker compose up -d
npm run migrate

add network to dockerfile for local cloud db

---

docker-compose.yml

creates network on docker compose up
docker network rm magick-network
docker compose up -d
docker network ls

create network on compose

---

packages/cloud-agent-manager/src/lib/CloudAgentManager.ts

Disabled unused heartbeats. The queries seemed to cause some issues.
Start magick with PINO_LOG_LEVEL=trace, observe that the manager's heartbeats don't go off

removes unused heartbeat that seemed to be causing weirdness

---

packages/core/server/src/api/index.ts
packages/core/server/src/app.ts
packages/core/shared/src/plugins/inspectorPlugin/index.ts
packages/core/shared/src/plugins/keyCodePlugin/index.ts
packages/editor/src/components/EventHandler.tsx
packages/editor/src/components/TabBar/TabBar.tsx
packages/editor/src/contexts/InspectorProvider.tsx
packages/editor/src/editor.ts
packages/editor/src/windows/TextEditorWindow/index.tsx

- Save spell difference when text editor data changed
- Publish text editor clear on tab change
- Auto save in text editor
- open more than one spells
- changed text editor data in one spell and keep switching between different spell tab to see if you lost data

Text editor

---

packages/core/shared/src/nodes/flow/CommandParser.ts
packages/core/shared/src/nodes/index.ts

Adds a Command Parser that parses commands such with an optional string array of valid commands.
/command arg1 arg2
into outputs:
command: 'command'
args: ['arg1','arg2']
isCommand: boolean
Use the node

add command parser node

---

package-lock.json
package.json
packages/agents/src/lib/Agent.ts
packages/agents/src/lib/AgentCommander.ts
packages/core/shared/src/communication/agentEventTypes.ts
packages/core/shared/src/spellManager/SpellRunner.ts
packages/plugins/rest/server/src/services/api/api.class.ts

Changed where we handled some errors, so we can listen to those errors from the http api
make a spell that always errors, use the rest api to run that spell, observe the error in the response

bubbles up agent errors to http api calls

---

packages/core/client/src/components/Drawer/OldSidebar/index.tsx
packages/core/shared/src/engine.ts
packages/core/shared/src/nodes/document/GetDocuments.ts
packages/core/shared/src/nodes/document/StoreDocument.ts
packages/editor/src/screens/DocumentWindow/DocumentModal.tsx
packages/editor/src/screens/DocumentWindow/DocumentTable.tsx

Reverted all Knowledge text back to Documents
Review Store Knowledge and Get Knowledge node and see if they have changed back to Store Document and Get Document respectively 

reverting Knowledge nodes text back to Documents

---

packages/core/server/src/hooks/spellmanagerHooks.ts
packages/core/server/src/services/spell-runner/spell-runner.class.ts
packages/core/shared/src/spellManager/SpellManager.ts
packages/core/shared/src/spellManager/SpellRunner.ts

SpellRunners (the class that runs spells) can't really handle multiple spell runs at the same time. They are pretty stateful, so that causes race conditions to pop up and results in weird behavior from agents that are receiving many messages at a time.
This changes how the SpellManager gets SpellRunners to run spells.
Before we had a mapping of SpellId -> SpellRunner, but now we have a mapping of SpellId -> Array<SpellRunner>
When we try to get a SpellRunner, we get the first "ready" runner in the array a spellId maps to.
If we don't find one, we create a new SpellRunner and add it to that array.
This we we have an automatically growing pool of spell runners
In the future we'll probably want this pool to auto clean itself, but it's likely the SpellRunner abstraction won't stick around, so …

adds an automatically expanding array of spellRunners for each spell

---

packages/core/shared/src/spellManager/SpellManager.ts

SpellRunners are created when an Agent is initialized.
The playtest window runs spells without an agent, so an Agent is never intialized.
The recent changes to SpellRunners changed how we store SpellRunners and ended up breaking the playtest window.
This fixes that bug and the playtest window

fixes playtest window

---

packages/core/shared/src/nodes/io/Input.ts
packages/core/shared/src/nodes/io/Spell.ts

The input node was referencing the value from the incoming data in a dumb way, just turning the object into an array and grabbing the zeroth index. This likely wasn't caught before since it only happens if you want to use more than one input node for a subspell. Since the entire run input object is passed into the run function, we needed to reference it differently.  
Now, we are using the node name from the nodes data (node.data.name) to properly reference the value for that input and returning that from the input.
Make sure you can pass a string value into a subspell from a second input node and then reference it internally in the subspell.
This image shows the subspell that was causing issues.
Rob Lennon is blocked by this, so we should get it in fast.  Hotfix to prod would be good.

Fix subspells

---

packages/core/shared/src/plugins/taskPlugin/task.ts

The filter function in the back propagation of the task plugin was not bound to the outer this scope, so it was failing on getting a task.  This fixes it.
IDE should work when using it.

Bind filter function in task back prop

---

packages/core/server/src/services/documents/documents.class.ts

Fetching documents via the get documents node was broken due to mis-query of a property on params.
Get documents node should work. 

Fix bug fetching documents

---

packages/core/server/src/services/events/events.class.ts
packages/editor/src/screens/EventWindow/index.tsx

Added a function with uses swap algorithm to reverse events array and display them from the recent last one 
1. Create a discord bot 
2. interact with it in spell text input
3. navigate to events window and check if the recent request you made is the one on the top on of events table

Display event in reverse chronological order

---

docker-compose.yml

Adds an s3 bucket with mino to the docker-compose file for local development

add minio s3 to docker-compose

---

apps/cloud-agent-manager/src/main.ts
apps/cloud-agent-worker/src/main.ts
package-lock.json
package.json
packages/cloud-agent-manager/src/lib/CloudAgentManager.ts
packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts
packages/config/src/config.ts

Added a mechanism to restart agents when a worker goes down.
Have an enabled agent locally.
run `npx nx serve @magickml/cloud-agent-manager-app`
run `npx nx serve @magickml/cloud-agent-worker-app`
wait for the worker to start an agent.
Kill the worker.
Run `npx nx serve @magickml/cloud-agent-worker-app`
After a few seconds, the worker should start the agent again.

Adds a heartbeat to restart agents when a worker goes down.

---

packages/core/client/src/components/Drawer/Newsidebar/index.tsx
packages/core/client/src/components/Drawer/OldSidebar/index.tsx
packages/core/client/src/components/Tooltip/index.tsx
packages/editor/src/DataControls/DataControls.tsx
packages/editor/src/components/Node/Node.tsx
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/screens/settings/SettingsWindow.tsx
packages/editor/src/windows/InspectorWindow.tsx
packages/plugins/bluesky/client/src/components/VariableModal.tsx
packages/plugins/bluesky/client/src/components/agent.component.tsx
packages/plugins/discord/client/src/components/VariableModal.tsx
packages/plugins/discord/client/src/components/agent.component.tsx
packages/plugins/github/client/src/components/VariableModal.tsx
packages/plugins/github/client/src/components/agent.component.tsx
packages/plugins/loop/client/src/components/loop.component.tsx
packages/plugins/rest/client/src/components/rest.component.tsx
packages/plugins/task/client/src/components/task.component.tsx
packages/plugins/twitter/client/src/components/VariableModal.tsx
packages/plugins/twitter/client/src/components/agent.component.tsx

Added disableInteractive prop to every Tooltip element so that the tooltip disappears when you hover off the element that triggers the popup. Previous behavior was that you would move your mouse from the element onto the tooltip and the tooltip would stay until you hover off the tooltip OR the element. If the tooltip goes on top of another button it gets in the way, especially annoying on the left nav bar.

disableInteractive on tooltips so they disappear

---

packages/agents/src/lib/Agent.ts
packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts
packages/plugins/rest/server/src/services/agentHttp/agentHttp.class.ts

Adds support for API calls to add properties to the event to they can set the sender, the client, the channel, etc.  Also adds support for passing through public variables, and secret overrides.
You can add these properties to a rest request, or try using the cloud PR here to send the properites via REST:
https://github.com/Oneirocom/Cloud/pull/495

Agent api overrides

---

packages/config/src/config.ts
packages/core/shared/src/spellManager/SpellManager.ts
packages/core/shared/src/spellManager/SpellRunner.ts
packages/plugins/googleai/server/src/functions/makeChatCompletion.ts
packages/plugins/googleai/server/src/functions/makeTextCompletion.ts
packages/plugins/googleai/server/src/functions/makeTextEmbedding.ts

Improves a few error logs from spell runner and spell manager
Adds a fallback palm api key to all palm completions for now.

Palm api fallback

---

packages/plugins/discord/server/src/connectors/discord.ts
packages/plugins/discord/shared/src/nodes/utils.ts

Change the discord connector to use the unique discord user ID instead of the discord username. Although the discord username is unique at the time the request is made, the user can change their username which could cause overlaps. The discord user ID is always the same for the user.

Discord snowflake

---

package-lock.json
package.json
packages/config/src/config.ts
packages/plugins/openai/server/src/functions/makeChatCompletion.ts
packages/plugins/openai/server/src/functions/makeTextCompletion.ts

Implemented exponential backoff and retry using axios-retry which wraps the axios instance. The max number of retries is specified in environment variable BACKOFF_RETRY_LIMIT (a good value seems to be 5 or 6 for this which is 10-20 seconds of retries)

retry and backoff when getting a 429 from openai text/chat completions

---

packages/core/server/src/services/agents/agents.ts
packages/core/server/src/services/spell-runner/spell-runner.class.ts
packages/core/server/src/sockets/channels.ts
packages/core/shared/src/spellManager/SpellRunner.ts

- Adds a bunch of loggers to run pipeline and session channels
- Switched a check in the main event publish filter from `projectId` to `!projectId`
Playtest should work in IDE again

Playtest fixes

---

packages/core/shared/src/nodes/io/Input.ts

The bug: when you have an input set as "default - input" then change the input type, for example changing to "Task", the node itself will still say "default - input". Reloading the page fixes the display error, and changing back to another type after that doesn't cause the bug, only when changing from "default" to something else.
The fix: The inspector control loops through each data control key and overrides them. The default input passes in a data control that overrides the input name (the displayed name) when data changes. Only the default input has this onData event, and the changing of the input name (the displayed name) is handled elsewhere in the app. I removed the onData event entirely and the bug was fixed. What was happening was one part of the code would change the input name, …

Fix bug with default input

---

packages/core/shared/src/cost-calculator.ts
packages/core/shared/src/nodes/text/GenerateText.ts
packages/core/shared/src/types.ts
packages/plugins/openai/server/src/functions/makeChatCompletion.ts
packages/plugins/openai/server/src/functions/makeTextCompletion.ts
packages/plugins/openai/shared/src/index.ts

- add model fine tuning to the generate text node for OpenAI
- make sure you can send a request to a fine tuned open AI model 
- select fine tuned gpt3.5 from main dropdown and then input your custom model name
- make sure normal chat generation works

Fine tuning

---

.gitignore
packages/core/shared/src/nodes/events/EventRecall.ts
packages/core/shared/src/nodes/events/EventStore.ts

stop lowercasing events and treat inspector data same as socket data for event type

Stop event store and recall from lowercasing things

---

packages/core/server/src/services/events/events.class.ts
packages/core/shared/src/nodes/events/EventRecall.ts

Switched filtering to use observer and sender explicitly rather than relying on the entities field, which was preventing getting other messages.  Also ensure that the observer is always in the query.
Event recall should work normally. You can also use this spell which simulates events being added to different channels to check recall.  At minimum all normal event recall functions should work.
[event-test.spell.json](https://github.com/Oneirocom/Magick/files/13385653/event-test.spell.json)

Fix filtering to use sender and observer explicitly
