Oneirocom/Magick

README.md

closes #43 
- Only space is required above the all contributors badge.

Broken link solved

---

.env
apps/agent-server/src/Agent.ts
apps/agent-server/src/World.ts
apps/agent-server/src/connectors/discord.ts
apps/client/.env
apps/client/src/workspaces/contexts/MagickInterfaceProvider.tsx
apps/server/src/events.ts
apps/server/src/spells/buildMagickInterface.ts
docker-compose.yml
packages/core/src/ProcessPython.ts
packages/core/src/components/events/EventQA.ts
packages/core/src/components/events/EventRecallWeaviate.ts
packages/core/src/components/index.ts
packages/core/types.ts
packages/plugins/src/social-connectors/instagram.ts
packages/systems/src/systems/weaviateInit.ts
packages/systems/src/systems/weaviate_events_schema.ts

Fixes the Discord agent by destructuring data into the full object.

Fix discord agent

---

apps/client/src/workspaces/contexts/MagickInterfaceProvider.tsx
apps/server/src/events.ts
apps/server/src/spells/buildMagickInterface.ts
packages/core/src/components/events/EventDelete.ts
packages/core/src/components/events/EventQA.ts
packages/core/src/components/events/EventRecallWeaviate.ts
packages/core/src/components/events/EventStoreWeaviate.ts
packages/core/src/components/index.ts
packages/core/types.ts
packages/systems/src/systems/weaviateInit.ts

Updates main to fix conflicts with latest weaviate events.

Update weaviate events

---

apps/client/src/workspaces/agents/windows/Agent.tsx

Better key input fields with obfuscation

Better key input fields

---

apps/client/src/App.tsx
apps/client/src/components/Drawer/Drawer.tsx
apps/client/src/components/MenuBar/MenuBar.tsx
apps/client/src/screens/Magick/components/EventHandler.tsx
apps/client/src/workspaces/agents/windows/AgentManagerWindow.tsx

Remove search corpus from windows

---

apps/client/src/workspaces/spells/DataControls/DataControls.jsx
apps/client/src/workspaces/spells/windows/EditorWindow/index.jsx
packages/client-core/src/editor.ts
packages/client-core/src/plugins/contextMenu/index.js
packages/client-core/src/plugins/contextMenu/main-menu.js
packages/client-core/src/plugins/contextMenu/menu.js
packages/client-core/src/plugins/contextMenu/node-menu.js
packages/client-core/src/plugins/contextMenu/react-menu/Item.jsx
packages/client-core/src/plugins/contextMenu/react-menu/Menu.jsx
packages/client-core/src/plugins/contextMenu/react-menu/context.js
packages/client-core/src/plugins/contextMenu/react-menu/index.jsx
packages/client-core/src/plugins/contextMenu/react-menu/style.module.scss
packages/client-core/src/plugins/contextMenu/rete.config.js
packages/client-core/src/plugins/contextMenu/style.module.scss
packages/client-core/src/plugins/contextMenu/utils.js
packages/client-core/src/plugins/contextMenu/vars.scss
packages/engine/src/nodes/variable/NumberVariable.ts

Context menu

---

packages/editor/src/components/ToolTip/index.tsx
packages/editor/src/screens/FineTuneManager/account/SignInForm.tsx
packages/editor/src/state/store.ts
packages/editor/src/workspaces/settings/SettingsWindow.tsx
packages/editor/src/workspaces/settings/styles.module.scss
packages/editor/src/workspaces/spells/windows/PlaytestWindow.tsx

moved openai key to settings window

---

apps/server/src/Agent.ts
apps/server/src/World.ts
package-lock.json
package.json
packages/editor/src/workspaces/agents/Agent.tsx
packages/plugin-discord/src/connectors/discord-voice.ts
packages/plugin-discord/src/connectors/discord.ts

Tested Discord Chat and Voice

---

apps/server/src/Agent.ts
apps/server/src/World.ts
package-lock.json
package.json
packages/editor/src/workspaces/agents/Agent.tsx
packages/engine/src/lib/plugin.ts
packages/plugin-discord/src/index.ts

Fix: Discord Start When discord_enabled is true

---

.gitignore
docs/notes/terminology.md
docs/notes/ux_improvements.md
package-lock.json
packages/editor/src/components/Select/Select.tsx
packages/engine/src/lib/nodes/ml/TextCompletion.ts

Resolving Issue #208 
https://github.com/Oneirocom/Magick/issues/208

Text completion field fix

---

apps/server/src/World.ts
apps/server/src/index.ts
apps/server/src/services/agents/agents.ts
packages/editor/src/components/Icon/Icon.tsx

The entity server does not crash the whole server when an error is found, the errors are logged to the `Agent` service. The editor would get the same error when trying to fetch from the `Agent` service
Fixes #53

Better Error Reporting for Entity Server

---

apps/server/src/Agent.ts
apps/server/src/World.ts
apps/server/src/index.ts
packages/plugin-discord/src/connectors/discord.ts
packages/plugin-discord/src/index.ts

Fixes #109 
Discord client is created or torn-down using the agent window, if for some reason the bot crashes, it is restarted again.

Discord Bot restarts when the bot crashes

---

.vscode/launch.json
apps/server/project.json
apps/server/src/services/spell-runner/spell-runner.class.ts
apps/server/src/services/spells/spells.class.ts
apps/server/src/services/spells/spells.ts
packages/editor/src/components/Modal/Modal.tsx
packages/editor/src/contexts/AppProviders.tsx
packages/editor/src/contexts/FeathersProvider.tsx
packages/editor/src/contexts/ModalProvider.tsx
packages/editor/src/contexts/ToastProvider.tsx
packages/editor/src/editor.ts
packages/editor/src/plugins/contextMenu/index.ts
packages/editor/src/plugins/reactRenderPlugin/index.tsx
packages/editor/src/screens/Magick/components/EventHandler.tsx
packages/editor/src/workspaces/agents/Agent.tsx
packages/editor/src/workspaces/spells/index.tsx
packages/editor/tsconfig.json
packages/engine/src/lib/plugins/modulePlugin/index.ts

Needs to be tested,  Should autosave after 5 seconds of inactivity on the composer.  Should also possibly fix websocket connection.

241 autosave

---

apps/client/.env
apps/client/src/main.tsx

Adds in code so we can handle loading from the iframe.

Add iframe message handling

---

packages/editor/src/plugins/contextMenu/main-menu.ts

fixed node appearing in wrong place when created

---

packages/client-core/src/components/Input/index.tsx
packages/editor/src/components/Modals/EditSpellModal.tsx
packages/editor/src/components/Modals/InfoModal.tsx
packages/editor/src/components/Modals/SaveAsModal.tsx
packages/editor/src/screens/Contract/Contract.tsx
packages/editor/src/screens/HomeScreen/screens/CreateNew.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/Agent.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/AgentItem.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/AgentPubVariables.tsx
packages/editor/src/workspaces/spells/DataControls/Input.tsx
packages/editor/src/workspaces/spells/windows/EventWindow/EventTable.tsx
packages/editor/src/workspaces/spells/windows/PlaytestWindow.tsx
packages/engine/src/lib/dataControls/TextInputControl.tsx
packages/plugin-discord/client/src/components/utils.tsx
packages/plugin-ethereum/client/src/components/agent.component.tsx
packages/plugin-ethereum/client/src/components/utils.tsx
packages/plugin-loop/client/src/components/loop.component.tsx
packages/plugin-rest/client/src/components/rest.component.tsx
packages/plugin-rest/client/src/components/utils.tsx

Fix inputs

---

apps/client/src/main.tsx
package-lock.json
packages/editor/src/editor.ts
packages/editor/src/workspaces/spells/windows/PlaytestWindow.tsx

Dropdown in playtest is now filtered to only show inputs that have been dropped down on the graph.

Only show inputs on graph in playtest window

---

packages/editor/src/screens/Magick/components/EventHandler.tsx
packages/editor/src/workspaces/spells/windows/PlaytestWindow.tsx
packages/server-core/src/services/spell-runner/spell-runner.class.ts

Might fix the socket issues.  needs testing.

Fix sockets maybe?

---

packages/engine/src/lib/nodes/ml/Generator.ts
packages/engine/src/lib/nodes/ml/TextCompletion.ts

added spell to the request

---

apps/agent/src/index.ts
apps/docs/docs/Magick REST API.postman_collection.json
apps/server/src/index.ts
packages/engine/src/lib/nodes/logic/Exclusive Gate.ts
packages/engine/src/lib/plugin.ts
packages/plugin-discord/server/src/connectors/discord-voice.ts
packages/plugin-discord/server/src/connectors/discord.ts
packages/plugin-ethereum/server/src/index.ts
packages/plugin-finetune/client/src/account/SignInForm.tsx
packages/plugin-rest/client/src/index.ts
packages/plugin-rest/server/src/index.ts
packages/plugin-rest/server/src/services/api/api.class.ts
packages/plugin-rest/server/src/services/api/api.schema.ts
packages/plugin-rest/server/src/services/api/api.ts
packages/server-core/src/AgentManager.ts
packages/server-core/src/app.ts
packages/server-core/src/buildMagickInterface.ts
packages/server-core/src/services/index.ts
packages/server-core/src/services/spell-runner/spell-runner.class.ts

REST API + agents working

---

packages/plugin-discord/server/src/connectors/discord.ts
packages/plugin-discord/server/src/index.ts
packages/server-core/src/Agent.ts
packages/server-core/src/AgentManager.ts

Fix Discord

---

packages/client-core/src/components/Select/index.tsx
packages/editor/src/workspaces/agents/AgentWindow/AgentDetails.tsx

fixed drop down select scrolling issue

---

packages/client-core/src/components/Input/index.tsx
packages/editor/src/App.css
packages/editor/src/index.ts
packages/editor/src/workspaces/agents/AgentManagerWindow.tsx
packages/editor/src/workspaces/agents/AgentWindowStyle.module.css
packages/editor/src/workspaces/agents/NewAgentWindow/AgentDetails.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/AgentItem.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/AgentPubVariables.tsx
packages/editor/src/workspaces/agents/NewAgentWindow/index.tsx
packages/plugin-discord/client/src/components/agent.component.tsx
packages/plugin-ethereum/client/src/components/agent.component.tsx
packages/plugin-loop/client/src/components/loop.component.tsx
packages/plugin-rest/client/src/components/rest.component.tsx
packages/server-core/src/services/agents/agents.schema.ts

added improved agent window UX

---

packages/editor/src/workspaces/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/workspaces/agents/AgentWindow/AgentPubVariables.tsx
packages/editor/src/workspaces/agents/AgentWindow/index.tsx
packages/engine/src/lib/nodes/variable/ArrayVariable.ts
packages/engine/src/lib/nodes/variable/BooleanVariable.ts
packages/engine/src/lib/nodes/variable/FewshotVariable.ts
packages/engine/src/lib/nodes/variable/NumberVariable.ts
packages/engine/src/lib/nodes/variable/StringVariable.ts
packages/engine/src/lib/plugins/modulePlugin/module.ts
packages/engine/src/lib/spellManager/SpellRunner.ts
packages/engine/src/lib/spellManager/runSpell.ts
packages/plugin-discord/server/src/connectors/discord.ts

Injects public variables into nodes and gets that all working. Some UI fixes.
Note -- there is a bug when deleting any variable, clears the whole thing.

Fix agent public variable editing in agent window

---

packages/editor/src/editor.ts
packages/editor/src/workspaces/agents/AgentManagerWindow.tsx
packages/editor/src/workspaces/contexts/EditorProvider.tsx
packages/editor/src/workspaces/contexts/styles.module.scss
packages/editor/src/workspaces/settings/SettingsWindow.tsx
packages/editor/src/workspaces/spells/windows/TextEditorWindow.tsx
packages/engine/src/lib/nodes/ml/Generator.ts
packages/plugin-finetune/client/src/account/SignInForm.tsx
packages/plugin-openai/client/src/index.ts
packages/plugin-openai/server/src/index.ts

Grid background zoom

---

.env
package-lock.json
package.json
packages/editor/src/editor.ts
packages/editor/src/workspaces/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/workspaces/settings/SettingsWindow.tsx
packages/editor/src/workspaces/spells/windows/TextEditorWindow.tsx
packages/engine/src/lib/nodes/ml/Generator.ts
packages/engine/src/lib/plugin.ts
packages/plugin-discord/client/src/components/agent.component.tsx
packages/plugin-discord/server/src/connectors/discord.ts
packages/plugin-discord/server/src/index.ts
packages/plugin-ethereum/client/src/components/agent.component.tsx
packages/plugin-finetune/client/src/account/SignInForm.tsx
packages/plugin-loop/server/src/index.ts
packages/plugin-openai/client/src/index.ts
packages/plugin-openai/server/src/index.ts
packages/plugin-twitter/client/src/components/agent.component.tsx
packages/plugin-twitter/client/src/index.ts
packages/plugin-twitter/server/src/connectors/twitter.ts
packages/plugin-twitter/server/src/index.ts
packages/server-core/src/Agent.ts

This PR adds the twitter plugin
DMs will be for another day

Add Twitter Connector

---

packages/client-core/src/components/IconButton/index.tsx
packages/client-core/src/components/Modal/index.module.scss
packages/client-core/src/components/Modal/index.tsx
packages/editor/src/components/Modal/Modal.tsx
packages/editor/src/components/Modal/modal.module.css
packages/editor/src/components/Modals/InfoModal.tsx
packages/editor/src/contexts/ModalProvider.tsx
packages/editor/src/plugins/areaPlugin/style.css
packages/editor/src/workspaces/agents/AgentWindow/AgentItem.tsx
packages/editor/src/workspaces/spells/windows/InspectorWindow.tsx
packages/plugin-discord/client/src/components/VariableModal.tsx
packages/plugin-discord/client/src/components/agent.component.tsx
packages/plugin-loop/client/src/components/loop.component.tsx
packages/plugin-rest/client/src/components/rest.component.tsx
packages/plugin-twitter/client/src/components/VariableModal.tsx

fixed help modal getting off

---

packages/engine/src/lib/dataControls/InputGenerator.ts
packages/engine/src/lib/dataControls/OutputGenerator.ts
packages/engine/src/lib/dataControls/TextInputControl.tsx
packages/engine/src/lib/nodes/apis/QueryGoogle.ts
packages/engine/src/lib/nodes/events/EventsToConversation.ts
packages/engine/src/lib/nodes/ml/CreateEmbedding.ts
packages/engine/src/lib/nodes/strings/JoinList.ts
packages/engine/src/lib/nodes/strings/PromptTemplate.ts
packages/engine/src/lib/nodes/strings/StringProcessor.ts
packages/engine/src/lib/nodes/utility/AlertMessage.ts
packages/engine/src/lib/nodes/utility/Cast.ts
packages/engine/src/lib/plugins/historyPlugin/action.ts
packages/engine/src/lib/plugins/historyPlugin/actions/connection.ts
packages/engine/src/lib/plugins/historyPlugin/actions/node.ts
packages/engine/src/lib/plugins/historyPlugin/history.ts
packages/engine/src/lib/plugins/historyPlugin/index.ts
packages/engine/src/lib/plugins/inspectorPlugin/DataControl.ts
packages/engine/src/lib/plugins/inspectorPlugin/Inspector.ts
packages/engine/src/lib/plugins/lifecyclePlugin/utils.ts
packages/engine/src/lib/plugins/multiCopyPlugin/index.ts
packages/engine/src/lib/types.ts

Removed //@ts-nocheck
I tried to leave the behavior as is. Could you check the creation of TypeError, if you want more graceful handling of null?

Fix typings for OutputGenerator.ts

---

packages/plugin-discord/server/src/connectors/discord.ts
packages/plugin-discord/server/src/index.ts
packages/server-core/src/agents/Agent.ts

This adds some error handlers for loading agent on Discord.

Handle no root spell and cases of empty Discord outputs

---

packages/editor/src/windows/ProjectWindow/index.tsx
packages/editor/src/windows/agents/AgentManagerWindow.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx

As it states, quick PR to include some missing auth headers

fix: include missing auth headers

---

apps/docs/docs/core-concepts/Fine Tuning.md

Update Fine Tuning.md

---

package-lock.json
package.json
packages/client-core/src/components/Drawer/ProjectWindow/index.tsx
packages/editor/src/windows/PlaytestWindow.tsx
packages/editor/src/windows/agents/AgentWindow/spellValidator.ts
packages/engine/src/lib/nodes/io/Request.ts
packages/engine/src/lib/nodes/object/JSONToObject.ts
packages/plugin-twitter/client/src/components/VariableModal.tsx
packages/plugin-twitter/client/src/components/agent.component.tsx
packages/plugin-twitter/client/src/index.ts
packages/plugin-twitter/client/vite.config.ts
packages/plugin-twitter/server/src/connectors/twitter.ts
packages/plugin-twitter/server/src/index.ts

This fixes some issues that came up.
NOTE: We need to re-enable spell validation of inputs. It wasn't working with Twitter so I disabled it.

Fixes for Twitter

---

packages/editor/src/windows/agents/AgentManagerWindow.tsx
packages/editor/src/windows/agents/AgentWindow/index.tsx

Push to prod

---

apps/server/migrations/20230120035818_agent.ts
packages/editor/src/components/MenuBar/MenuBar.tsx
packages/editor/src/components/Modals/InfoModal.tsx
packages/editor/src/components/TabBar/TabBar.tsx
packages/editor/src/components/Workspace.tsx
packages/editor/src/screens/Magick/Magick.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx

fixed bugs

---

packages/core/shared/src/agents/AgentManager.ts
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx

This fixes the dosctore and merges https://github.com/Oneirocom/Magick/pull/574

Fix docstore

---

packages/core/server/src/app.ts
packages/core/server/src/vectordb.ts

Corrected: File not found error
Adds: Docs for VectorDB

Fix: File Not Found Error

---

.env
plugins/openai/server/src/functions/makeChatCompletion.ts

also added in the missing supabase vars to .env

604 bug 4 type errors on build in makechatcompletionts

---

packages/editor/src/windows/RequestWindow/index.tsx

Currently requests window is broken in the cloud, due to some bad code. This fixes it.

Fix requests window

---

packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx

Error when trying to change spell, this fixes it.

Fix agent root spell selector

---

packages/core/client/src/components/Drawer/index.tsx
packages/core/client/src/components/index.ts
packages/core/client/src/contexts/ProjectWindowContext.tsx
packages/core/client/src/contexts/index.ts
packages/core/client/src/index.ts
packages/core/shared/src/types.ts
packages/editor/src/components/MenuBar/MenuBar.tsx
packages/editor/src/contexts/PubSubProvider.tsx
packages/editor/src/layouts/MainLayout/MainLayout.tsx

You can show up project window via window menu option or using hotkey

added project window to window menu options

---

packages/core/server/src/vectordb.ts
packages/core/shared/src/plugins/socketPlugin/index.ts
packages/core/shared/src/spellManager/SpellManager.ts

the check was ifExists, but should have been ifNotExists
Adding a ! fixed it, added initial index write too just in case

Fix issue where local vectordb erased

---

packages/core/shared/src/plugin.ts
plugins/loop/server/src/index.ts

This PR fixes the loop connector disable and restart.

Fix Disable Loop Connector

---

.env
apps/server/src/index.ts
packages/core/server/src/app.ts
packages/core/server/src/customEmbeddings.ts
packages/core/server/src/dbSetup.ts
packages/core/server/src/index.ts
packages/core/server/src/vectordb.ts
packages/core/shared/src/plugin.ts

Fix: Removed Supabase Client

---

packages/core/client/src/components/Modal/index.tsx
packages/editor/src/plugins/contextMenu/react-menu/Menu.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
plugins/bluesky/client/src/components/VariableModal.tsx
plugins/bluesky/client/src/components/agent.component.tsx

added immediate focus on search when context menu show up and fixed bugs

---

.env

Create small change to trigger CI/CD test on cache

---

.env
packages/core/server/src/services/events/events.class.ts
packages/core/server/src/vectordb.ts
packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts
packages/core/shared/src/nodes/text/GenerateText.ts
plugins/openai/server/src/functions/makeTextCompletion.ts

This PR pushes fixes for the embedding nodes for testing in prod

Push latest to prod

---

packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts

Fix type errors for embeddings in development build.

Fix type errors for embeddings

---

plugins/avatar/client/src/components/Chat.jsx

Fixes: https://github.com/Oneirocom/Magick/issues/715
Here are some screenshots for testing steps below:
step1]
First, click the "Create New" button on the home page.
step2]
Second, select the Starter template and write down the spell name.
step3]
Third, On the spell window, input any text in Playtest section. 
If you can see the echo back, that means that spell works correclty.
step4]
On the main menu, please click avatar button to redirect. On the avatar page, you can see Character, Personality window, Chatbox window and Spell list.
Please select the Spell what you have just created.
step5]
Next, please input any text in chatbox and click the send button. You can see Eliza's text and listen her voice with her Lip sync.
step6]
Finally, If you want to change the Character, you can …

Test StarterSpell and avatar screenshots

---

pull_request_template.md

I added a basic pull request template to the root of the project 
I don't think we can test this, it has to be in the default branch in order to be used

Created a basic pull request template

---

packages/core/shared/src/plugins/inspectorPlugin/Inspector.ts
packages/editor/src/DataControls/DataControls.tsx
packages/editor/src/DataControls/Form.tsx
packages/editor/src/DataControls/SocketGenerator.tsx
packages/editor/src/contexts/InspectorProvider.tsx
packages/editor/src/plugins/contextMenu/node-menu.ts
packages/editor/src/windows/DebugConsole/index.tsx
packages/editor/src/windows/TextEditorWindow/index.tsx

- Create code node
- Try Adding/Removing input sockets to it and ensure that changes are being reflected in the code editor as well accurately.
- You can refer to the video attached in the comment
- For Python code node improvement is needed (I will talk to Moon about it)
https://user-images.githubusercontent.com/58092199/234518473-572d069c-8dcd-4d5d-9805-7f9fac6d30eb.mov

Fixed add/remove input sockets and reflect changes in the javascript code editor

---

apps/server/migrations/20230422231456_task.ts
packages/core/server/src/customEmbeddings.ts
packages/core/server/src/services/documents/documents.class.ts
packages/core/server/src/vectordb.ts
packages/core/shared/src/nodes/document/StoreDocument.ts
plugins/discord/server/src/connectors/discord.ts

Updated customEmbeddings according to the new createTextEmbeddings
Store Document node should work in the graph directly

Fix: Store Document

---

packages/core/client/src/components/Drawer/index.tsx
packages/core/server/src/services/documents/documents.class.ts
packages/core/shared/src/config.ts
packages/core/shared/src/nodes/document/GetDocuments.ts
plugins/avatar/client/src/App.jsx
plugins/avatar/client/src/App.module.css
plugins/avatar/client/src/components/Chat.jsx
plugins/avatar/client/src/components/Chat/ChatBox.jsx
plugins/avatar/client/src/components/DragDrop/DragDrop.jsx
plugins/avatar/client/src/components/DragDrop/DragDrop.module.css
plugins/avatar/client/src/components/Scene/Avatar.jsx
plugins/avatar/client/src/components/Scene/Scene.jsx
plugins/avatar/client/src/components/Sxp/Sxp.jsx
plugins/avatar/client/src/hooks/useLipSync.js
plugins/avatar/client/src/hooks/useVrm.js
plugins/avatar/client/src/utils/constants.jsx
plugins/task/server/src/index.ts

Document recall node wasn't working. This fixes it by injecting the feathers app into the node and using that. It also dramatically simplifies how we're handling query parameters.
Store and recall document should work.

Fix documents

---

packages/core/shared/src/config.ts
plugins/avatar/client/src/App.jsx
plugins/avatar/client/src/App.module.css
plugins/avatar/client/src/components/Chat.jsx
plugins/avatar/client/src/components/Chat/ChatBox.jsx
plugins/avatar/client/src/components/DragDrop/DragDrop.jsx
plugins/avatar/client/src/components/DragDrop/DragDrop.module.css
plugins/avatar/client/src/components/Scene/Avatar.jsx
plugins/avatar/client/src/components/Scene/Scene.jsx
plugins/avatar/client/src/components/Sxp/Sxp.jsx
plugins/avatar/client/src/hooks/useLipSync.js
plugins/avatar/client/src/hooks/useSpellList.js
plugins/avatar/client/src/hooks/useVrm.js
plugins/avatar/client/src/utils/constants.jsx

The avatar plugin has been changed with R3f

Updated avatar plugin with R3f 

---

apps/docs/docs/nodes/Overview.md

Updated the placeholder node overview.
Read for grammar and meaning.

Remove Nodes documentation placeholder.

---

scripts/check-docker.js

docker-compose is deprecated and hits EOL in june this year, so this change keeps us up to date
https://docs.docker.com/compose/compose-v2/

updates docker script to use the new docker compose command

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.md

Add auto labeling to Github issues.
Check if the submission of a new issue or enhancement auto labels.

Add auto labeling to Github issues.

---

scripts/config-plugins.js

This fixes #796 by checking to see requiring a module fails.

Handle `npm install` edge cases.

---

.vscode/settings.json
package-lock.json
package.json
packages/core/shared/src/nodes/index.ts
packages/core/shared/src/nodes/utility/Error.ts
packages/core/shared/src/plugins/consolePlugin/MagickConsole.ts
packages/core/shared/src/plugins/consolePlugin/index.ts
packages/core/shared/src/plugins/socketPlugin/index.ts
packages/core/shared/src/plugins/taskPlugin/index.ts
packages/editor/src/components/MenuBar/MenuBar.tsx
packages/editor/src/windows/DebugConsole/index.tsx

- fix node highlighting
- fix node error highlighting
- fix ide console logging
- fix ide error console logging
- add error utility node for throwing an error
Run a spell.  Should glow green and report to console.
Add new error node.  Run spell.  Node should turn red.  Error should be reported in red to the console.

Reporting fixes

---

.env
apps/server/migrations/20230120035818_agent.ts
package-lock.json
package.json
packages/core/client/src/components/Drawer/ProjectWindow/index.tsx
packages/core/server/src/services/projects/projects.class.ts
packages/core/shared/src/plugin.ts
packages/core/shared/src/schemas.ts
packages/editor/src/components/EventHandler.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/windows/agents/AgentWindow/spellValidator.ts

This PR fixes importing projects. There were some issues with data validation. Also, when exporting, projects are pretty printed as JSON so that they can be version controlled.
Open the project window.
Make a project with a spell and a an agent. Export it. Reimport it. You should now have 2 of each.

Fix project import

---

packages/core/shared/src/agents/Agent.ts
plugins/discord/server/src/connectors/discord.ts
plugins/discord/server/src/index.ts

Discord connector isn't working
Make a default discord bot and try to talk to it. Should work

Fix Discord Connector

---

package.json
packages/core/client/src/templates/spells/Starter.spell.json
packages/core/shared/src/nodes/io/Output.ts
packages/core/shared/src/plugins/inspectorPlugin/Inspector.ts
packages/core/shared/src/spellManager/SpellRunner.ts
packages/core/shared/test/nodes/utility/Template.spell.json
plugins/discord/client/src/templates/spells/Discord Bot.spell.json
plugins/rest/client/src/templates/spells/REST API.spell.json

- added a default value for outputs
- removed some unused code
- fixed outputs in spell templates
- dropping down the start spell and hooking to discord agent should return responses on discord
- fixes bugs where users report that the three dots are typing, but no response comes.

Discord output fixes

---

packages/core/server/src/services/documents/documents.class.ts
packages/core/server/src/services/events/events.class.ts
packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts

- Added cosine similarity and distance values in embedding based searches
- FindTextEmbedding: Altered query object
Can be tested using the spells
Distance should be 0 for same content values and the similarity values should be 1 for same content values.

Feat: Added cosine similarity values

---

apps/docs/docs/api/index.md
packages/core/client/src/components/CustomizedSwitch/index.tsx
packages/core/client/src/components/Input/index.tsx
packages/core/client/src/components/index.ts
packages/core/shared/src/nodes/text/GenerateText.ts
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/windows/agents/AgentWindow/AgentPubVariables.tsx
plugins/openai/server/src/functions/makeChatCompletion.ts

- Changed agent enable button and remove unnecessary action to hit the update button after hitting enable button
- Fixed agent secrets when a new agent is created to fix #687
- Fixed updating public variables at agent page
- Try enabling/disabling the agent
- create a new agent and configure the same open ai as the other agents are using

changed enable agent button and fixed a bug with agent secrets

---

apps/docs/docs/api/index.md
packages/core/client/src/components/Drawer/ProjectWindow/index.tsx
packages/core/server/src/services/events/events.class.ts
packages/editor/src/plugins/reactRenderPlugin/Upload.tsx
packages/editor/src/windows/DocumentWindow/DocumentTable.tsx
packages/editor/src/windows/DocumentWindow/index.tsx
packages/editor/src/windows/EventWindow/EventTable.tsx
packages/editor/src/windows/EventWindow/index.tsx
packages/editor/src/windows/RequestWindow/RequestTable.tsx
packages/editor/src/windows/RequestWindow/index.tsx
plugins/discord/client/src/components/agent.component.tsx
plugins/finetune/client/src/files/GetRecordsButton.tsx
plugins/task/client/src/windows/TaskWindow/TaskTable.tsx
plugins/task/client/src/windows/TaskWindow/index.tsx

Added auth headers to missing fetch requests.
Auth headers now use a standard token regardless of local/cloud.
Make sure all fetch requests are working.
Events/documents/requests/fetching spells/etc. should all be working in both cloud and local
N/A

client side headers

---

plugins/avatar/client/src/components/Scene/Scene.jsx

Scene has been updated for WebXR
We can use VR device or google extension - WebXR API Emulator

webXR scene

---

packages/core/client/src/components/Drawer/ProjectWindow/index.tsx
packages/core/shared/src/functions/expandVector.ts
packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
packages/core/shared/src/nodes/events/EventDestructure.ts
packages/core/shared/src/nodes/index.ts
packages/core/shared/src/nodes/io/SpellByName.ts
plugins/discord/server/src/connectors/discord.ts
plugins/discord/server/src/index.ts
plugins/googleai/server/src/functions/makeChatCompletion.ts

Remove "data" field from project export
Retype embeddings
Add "Spell By Name" node, similar to a skill but different inputs (probably can consolidate with skill)

New Eliza Fixes

---

packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
packages/core/shared/src/nodes/flow/IsNullOrUndefined.ts
packages/core/shared/src/nodes/io/Respond.ts
packages/core/shared/src/nodes/io/SpellByName.ts
packages/core/shared/src/nodes/text/TextVariable.ts
packages/core/shared/src/plugins/modulePlugin/module-manager.ts
packages/editor/src/screens/HomeScreen/AllProjects.tsx
packages/editor/src/state/api/spells.ts
plugins/bluesky/server/src/index.ts
plugins/discord/server/src/connectors/discord.ts
plugins/googleai/server/src/functions/makeChatCompletion.ts
plugins/task/client/src/windows/TaskWindow/TaskTable.tsx

This PR alphabetically sorts spells in the Spellbook. This is very handy :)

Fixes for ELIZA

---

packages/core/server/src/services/projects/projects.class.ts

Fixed validation error on agent creation
import Eliza! 😄

fix importing projects validation error

---

packages/core/client/src/components/Drawer/ProjectWindow/index.tsx
packages/core/shared/src/nodes/flow/IsNullOrUndefined.ts
packages/core/shared/src/nodes/io/SpellByName.ts
packages/editor/src/editor.ts
packages/editor/src/plugins/autoArrangePlugin/auto-arrange.js
packages/editor/src/plugins/autoArrangePlugin/board.js
packages/editor/src/plugins/autoArrangePlugin/cache.js
packages/editor/src/plugins/autoArrangePlugin/index.js
packages/editor/src/plugins/commentPlugin/index.js
packages/editor/src/windows/TextEditorWindow/index.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx

Fix Is Null or Undefined node
Fix project export
Fix agent project import
Etc etc

More Eliza Fixes

---

packages/core/server/src/services/documents/documents.class.ts
packages/core/shared/src/nodes/document/GetDocuments.ts
packages/core/shared/src/nodes/embedding/CosineSimilarity.ts
packages/core/shared/src/nodes/index.ts
packages/core/shared/src/nodes/number/Equal.ts
packages/core/shared/src/nodes/number/GreaterThan.ts
packages/core/shared/src/nodes/number/GreaterThanOrEqual.ts
packages/core/shared/src/nodes/number/LessThan.ts
packages/core/shared/src/nodes/number/LessThanOrEqual.ts
packages/core/shared/src/types.ts
plugins/discord/server/src/connectors/discord.ts

Add logic nodes (>, <, ==, >=, <=) for numeric types. Useful for things like similarity thresholds.

Add numeric logic nodes

---

packages/core/server/src/services/spells/spells.schema.ts
packages/core/shared/src/schemas.ts

Made spell ids optional in the spell schema

Changes id to be optional

---

packages/core/server/src/services/spells/spells.schema.ts
packages/core/shared/src/schemas.ts

made the spell schema more accurate AND resolved some typscript issues

Fixes some typescript errors relating to spell.id

---

plugins/avatar/client/src/components/Scene/Scene.jsx

Removed unnecessary button on scene component

remove button from scene

---

.all-contributorsrc

Just added myself to the contributors

Added benbot to contributors

---

packages/core/shared/src/nodes/io/Spell.ts

Just updates the doc with the new node name

Change Module to Spell

---

apps/docs/docs/api/index.md

Restore index.md from `https://github.com/Oneirocom/Magick/pull/868`
Check the dinosaurs.

Restore index.md

---

packages/core/server/src/services/spells/spells.schema.ts

I accidentally committed something that broke project imports in spell.schema.ts
Import Eliza!
Sorry about that!

Fix project imports

---

packages/editor/src/windows/agents/AgentManagerWindow.tsx
packages/editor/src/windows/agents/AgentWindow/AgentDetails.tsx
plugins/avatar/client/src/hooks/useSpellList.ts
plugins/task/client/src/windows/TaskWindow/index.tsx

Fixed headers on AgentWindowManager and avatar plugin that still used DEFAULT_USER_TOKEN directly.
Make sure the vrm and AgentWindowManagers requests work
N/A

update agentwindow and avatar plugin headers

---

.github/workflows/ossf.yml

Add the OSSF Scorecard
Check if the scorecard appears
Requirement for enterprise.

Run the OSSF Scorecard.

---

packages/core/shared/src/agents/Agent.ts
packages/core/shared/src/agents/AgentManager.ts
packages/core/shared/src/config.ts

added configurable timers for agent updates and agent pings
make an agent, ensure that they get updated according to the new environment variable

adds configurable agent update and ping timers

---

package-lock.json
package.json
packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/spells/spells.ts

Merge latest into https://github.com/Oneirocom/Magick/pull/942 to fix project import

Fix project import with multiple project IDs

---

packages/core/server/src/services/projects/projects.class.ts
packages/core/server/src/services/spells/spells.ts

Fixed project spell import
Project import

Fix: Project Import Spell fix

---

packages/core/server/src/services/events/events.class.ts
packages/editor/src/components/Node/Node.tsx
packages/editor/src/windows/settings/SettingsWindow.tsx

- Added considering max count on event recall when using embeddings

added max count on event recall when using embeddings

---

packages/editor/src/components/Modals/SaveAsModal.tsx
packages/editor/src/screens/HomeScreen/CreateNew.tsx
packages/editor/src/screens/HomeScreen/HomeScreen.tsx

- UUID in Create new
- UUID in Import Spell
Null spell id in create new
Server Side Id creation removed in #943

Fix: Spell Creations Bug

---

apps/docs/docs/api/index.md
packages/agents/src/lib/Agent.ts
packages/core/server/src/services/agents/agents.class.ts
packages/core/shared/src/config.ts

Added environment variables for redis.
Ensure that local works and that this runs in dev. be sure to set the environment vars in heroku

adds redis options for username and password

---

apps/agent/src/index.ts
apps/server/src/index.ts

HOTFIX exceptions in agent

---

packages/core/client/src/components/Drawer/SetAPIKeys.tsx
packages/core/shared/src/nodes/document/DocumentToContent.ts
packages/core/shared/src/nodes/document/GetDocuments.ts
packages/core/shared/src/nodes/document/StoreDocument.ts
packages/core/shared/src/nodes/embedding/CosineSimilarity.ts
packages/core/shared/src/nodes/embedding/ExtractRelationship.ts
packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts
packages/core/shared/src/nodes/events/EventDestructure.ts
packages/core/shared/src/nodes/events/EventRecall.ts
packages/core/shared/src/nodes/events/EventStore.ts
packages/core/shared/src/nodes/events/EventsToConversation.ts
plugins/googleai/shared/src/index.ts
plugins/openai/shared/src/index.ts

added embedding socket type to all embedding inputs and outputs

added embedding socket type to all embedding inputs and outputs

---

apps/docs/docs/api/index.md
packages/core/shared/src/nodes/array/GetValueFromArray.ts
packages/core/shared/src/nodes/boolean/LogicalOperator.ts
packages/core/shared/src/nodes/number/InRange.ts
packages/core/shared/src/nodes/number/NumberVariable.ts
packages/core/shared/src/nodes/object/MergeObjects.ts
packages/core/shared/src/nodes/text/ComplexStringMatcher.ts
packages/core/shared/src/nodes/utility/Cast.ts
packages/editor/src/windows/DebugConsole/index.tsx
plugins/rest/client/src/components/rest.component.tsx

- fixed logical operator wrong operation type
- Is Null or Undefined node is fine
- Fixed Get Values from the Array node label
- Fixed number variable output type
- Fixed cast node
- Fixed Text rule matcher Minimum/Maximum
- Fixed merge objects throwing an error when don't pass an optional object
- Fixed In Range throwing error when no input numbers
- Fixed URL in the agent Rest API popup

fixed various bugs

---

apps/cloud-agent-worker/src/plugins.ts
apps/docs/docs/api/index.md
packages/core/shared/src/nodes/text/CombineText.ts
packages/editor/src/screens/agents/AgentManagerWindow.tsx
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/screens/agents/AgentWindow/AgentPubVariables.tsx
packages/editor/src/screens/agents/AgentWindow/index.module.scss
packages/editor/src/screens/agents/AgentWindow/index.tsx

- fixed agent window public variables when root spell changed
- fixed combine text node
- Change the root spell's public variable
- revisit the agent window
- create combine text node and pass two the text variables to combine without setting delimiter
- press send button at playtest

Fixed agent window

---

plugins/avatar/client/src/App.tsx
plugins/avatar/client/src/hooks/useVrm.ts
plugins/avatar/client/src/utils/constants.jsx

We are showing default model when loading of other one is failed.
Drag/drop vrm files. If that vrm file is non-standard one, the page will keep showing the first avatar.

Default model showing

---

apps/cloud-agent-worker/src/plugins.ts
apps/docs/docs/api/index.md
packages/core/shared/src/config.ts
packages/core/shared/src/dataControls/InputGenerator.ts
packages/core/shared/src/nodes/array/ArrayVariable.ts
packages/editor/src/components/Workspace.tsx

- Fixed array keep empty values
#777

Fix array variable

---

plugins/avatar/client/src/components/Scene/Avatar.jsx
plugins/avatar/client/src/components/Scene/Watch.jsx
plugins/avatar/client/src/hooks/useVrm.ts
plugins/avatar/client/src/hooks/useVrmMixamoAnimations.ts

fixed some vrm models direction.
drag/drop any vrm models on the avatar page.

Fix wrong direction of some VRM models 

---

packages/editor/src/components/Modals/SaveAsModal.tsx

Bug in the "Save As" where the ID is not set properly. Might be from a previous merge conflict that was uncaught. Small fix :)

Fix "save as"

---

packages/core/shared/src/nodes/flow/WaitForAll.ts
packages/editor/src/components/Modals/SaveAsModal.tsx

- Business logic for wait for all node
- #805 
Recreate the graph in the screenshot below and send some text in the playtest window. 

made wait for all node working

---

packages/core/shared/src/nodes/boolean/IsVariableTrue.ts

Reverts Oneirocom/Magick#997
seems like that didn't resolve
See #1035 for details
Should resolve #1035

Revert "fix Is Variable True testing value "

---

packages/plugins/avatar/client/src/components/Scene/Avatar.jsx
packages/plugins/avatar/client/src/components/Scene/Watch.jsx
packages/plugins/avatar/client/src/hooks/useVrm.ts

we can load only VRM1 files for now
drag/drop any vrm files. if it is vrm0 or invalid file, then we will show the default avatar.

Restrict to VRM1 and ignore forward fixing

---

packages/agents/src/lib/Agent.ts
packages/core/server/src/sockets/channels.ts
packages/plugins/avatar/client/src/components/Chat/ChatBox.tsx

Fixed a couple pubsub issues that were breaking the chatbox page
1. Make an echo spell
2. Attach that spell to an agent
3. Observe the avatar chatbox echoing your messages
Should resolve #1046 
Should unblock #1029

removed hardcoded agentId from avatar page chatbox

---

packages/core/shared/src/nodes/io/Output.ts

Right now, "default" output works, but sending output to a specific out isn't working. This fixes it. Tested with taking a tweet input and outputting to a Discord channel by adding a channel ID to the event

Fix output

---

packages/plugins/avatar/client/src/App.tsx
packages/plugins/avatar/client/src/hooks/useVrm.ts

We are showing notification when new avatar is loaded.
Drag/Drop any vrm files on the avatar page.

Toast in avatar page

---

packages/core/server/src/services/requests/requests.ts
packages/core/shared/src/nodes/text/ComplexStringMatcher.ts

- Fixed this issue: #884 
- I don't exactly know what other rules match to test them, @lalalune mentioned the problem on other rules in this #1011 

fix max and min rules

---

packages/core/server/src/services/requests/requests.ts
packages/core/shared/src/nodes/text/ComplexStringMatcher.ts

Revert "fix max and min rules"

---

packages/core/client/src/components/Modal/index.tsx
packages/editor/src/screens/DocumentWindow/DocumentModal.tsx
packages/editor/src/screens/DocumentWindow/DocumentTable.tsx

I first made sure we don't close the modal any time we submit something and then I add a timeout so that we can retrieve all available docs including the one we just uploaded lastly i also added message toast and a loader so that the user can see what's happening  
Navigate to documents window and then try to upload a document

Fixing state on documents window

---

package-lock.json
package.json
packages/core/shared/src/nodes/array/ExtractFromArray.ts
packages/core/shared/src/nodes/index.ts
packages/core/shared/src/nodes/text/GetLength.ts
packages/core/shared/src/nodes/text/ReplaceText.ts
packages/core/shared/src/nodes/text/SplitBySentence.ts
packages/core/shared/src/nodes/text/Trim.ts

This PR adds some useful new nodes
- Extract From Array -- make a new array from the value of key inside the input array. So if you have a document and you just want an array of the content, values, for example
- Get Length -- get the length of string
- Split By Sentence -- Split a string down to a under a maximum length, but in a sentence. So if you want to write a tweet but you want each tweet to be coherent sentences (or just get the first array value for a single tweet)
- Trim -- Trim the whitespace at beginning and end of a string

Add some new nodes

---

packages/plugins/discord/server/src/connectors/discord.ts
packages/plugins/discord/server/src/index.ts
packages/plugins/twitter/client/src/components/VariableModal.tsx
packages/plugins/twitter/server/src/connectors/twitter.ts

This fixes some things on Twitter, notable the feed handler and DM handler on/off switches, as well as Discord, notably cleanup of the DM and Chat handler and differences.

Twitter and Discord fixes

---

package-lock.json
package.json
packages/plugins/github/server/src/connectors/github.ts
tsconfig.base.json

added an extra error check and a missing dep that's breaking dev

Added extra error check and dependencies for github plugin

---

packages/core/shared/src/config.ts
packages/core/shared/src/logger/index.ts

Adds environment var to change pino logs

Adds environment var to change pino log level

---

packages/core/shared/src/nodes/text/ComplexStringMatcher.ts

- Complex string matcher
- Create below spell and try validating and matching operations
- Since this node performs matching and validation operations, note that validity takes high priority over matching when both operations are performed simultaneously.

improved string text matcher

---

packages/editor/src/plugins/highlightPlugin/index.ts
packages/editor/src/plugins/reactRenderPlugin/Socket.tsx
packages/editor/src/screens/RequestWindow/RequestTable.tsx

Fix node connection path

---

packages/agents/src/lib/Agent.ts
packages/agents/src/lib/AgentManager.ts
packages/core/shared/src/nodes/events/EventStore.ts
packages/plugins/search/shared/src/nodes/SearchGoogle.ts
packages/plugins/task/client/src/windows/TaskWindow/index.tsx

Removes some console.logs and calls automatic formatting on some files

remove console logs

---

apps/docs/docs/connectors/Discord.md

The comments are causing our docs engine to throw a fit. This removes the commented code.

Fix discord markdown file

---

packages/cloud-agent-manager/src/lib/MessageQueues/BullMQ.ts

Fixes a ref to @magickml/core that should be @magickml/config

Fix package reference for bullMQConnection

---

apps/client/.eslintrc.json
apps/server/.eslintrc.json

Adds some rules to ignore generated files

Add eslint ignore rules

---

.env
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx

I made sure i sort  spellList array before being mapped in options tag 
1. Create like 5 spells in a project 
2. navigate to agent window 
3. try selecting a Root Spell

Fix Agent spell list order

---

.env
packages/editor/src/screens/DocumentWindow/DocumentTable.tsx

I changed setTimeout from the UpdatecCallBack in the handle save function to the SetCreateMode.
- Navigate to the document menu as well as the page
- Click on Create new 
- Select the model as `text-embedding-002`
- Type `pdf` and upload a pdf document 
Then click on the `GENERATE EMBEDDINGS AND SAVE`, and the uploaded files will be reflected on the screen automatically.

fixing document state

---

package-lock.json
package.json

just moved a dev dep to regular deps

moves anthropic sdk to regular deps

---

.env

Cleans .env file. It got messed up

fixed botched .env

---

apps/client/src/main.tsx

adds logging so we can track blackscreen issues

add logging to IDE setup

---

apps/client/src/main.tsx

swapped some logs around to get logging NOW

swapped to info on editor

---

.env

cleans up .env file

---

packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx
packages/editor/src/screens/agents/AgentWindow/tooltip_texts.ts
packages/plugins/bluesky/client/src/components/VariableModal.tsx
packages/plugins/bluesky/client/src/components/agent.component.tsx
packages/plugins/discord/client/src/components/VariableModal.tsx
packages/plugins/discord/client/src/components/agent.component.tsx
packages/plugins/github/client/src/components/VariableModal.tsx
packages/plugins/github/client/src/components/agent.component.tsx
packages/plugins/loop/client/src/components/loop.component.tsx
packages/plugins/rest/client/src/components/rest.component.tsx
packages/plugins/task/client/src/components/task.component.tsx
packages/plugins/twitter/client/src/components/VariableModal.tsx
packages/plugins/twitter/client/src/components/agent.component.tsx

I wrapped Tooltip component from mui on   every title on agent details window
1. navigate to agents window
2.  create an agent if you don't have one
3. hover over every title on agent details
[Screencast from 14.07.2023 14:34:19.webm](https://github.com/Oneirocom/Magick/assets/55635977/4490cc54-3e89-437a-8ab8-f06998a47750)

adding tooltip to all agent window inputs

---

packages/core/client/src/components/Drawer/index.tsx
packages/editor/src/components/Node/Node.tsx
packages/editor/src/plugins/reactRenderPlugin/Socket.tsx

I wrapped Tooltip component around input and output sockets 
1. Create a spell 
2. Hover on any socket of a node in that spell 
[Screencast from 13.07.2023 21:06:26.webm](https://github.com/Oneirocom/Magick/assets/55635977/a7153d2f-269c-4885-acea-6059ce8dc951)

Adding Tooltip to each socket connector 

---

packages/core/shared/src/nodes/index.ts
packages/core/shared/src/nodes/text/GenerateUUID.ts

add uuid node

---

packages/cloud-agent-manager/src/lib/Reporters/PgNotifyReporter.ts

adds logs to pg notify reporter

---

apps/cloud-agent-manager/src/main.ts
packages/cloud-agent-manager/src/lib/CloudAgentManager.ts
packages/cloud-agent-manager/src/lib/Reporters/FeathersSyncReporter.ts
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx

Uses feathers-sync instead of pgNotify for agent updates.

swaps agents manager to use feathers sync

---

packages/core/server/src/services/agents/agents.schema.ts

Added rootSpellId to the feathers service schema

add rootSpellId to feathers service schema

---

package.json
packages/agents/src/lib/Agent.ts
packages/cloud-agent-manager/src/lib/Reporters/FeathersSyncReporter.ts
packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts
packages/core/client/src/providers/FeathersProvider.tsx
packages/core/server/src/services/agents/agents.class.ts
packages/core/shared/src/spellManager/SpellManager.ts
packages/core/shared/src/spellManager/SpellRunner.ts

fixes the playtest window, makes logs less noise, adds deletion events to agents, adds a new endpoint for pinging agents, and changed npm run dev to act like npm run cloud

Fixing agents

---

.env

Add intent plugin to .env

---

packages/core/client/src/components/Drawer/Newsidebar/index.tsx
packages/editor/src/components/Node/Node.tsx
packages/editor/src/components/Workspaces.tsx
packages/editor/src/screens/Magick/Magick.tsx
packages/editor/src/state/tabs.ts

- I have changed the left sidebar menu to be opened (Agents, Documents, Events, Requests, Tasks, Avatar and Settings) as the tabs instead of pages.
- Open the AIDE and click on those left sidebar menus
https://github.com/Oneirocom/Magick/assets/55635977/af2d14e7-77a3-407c-be37-087f831423f0

adding open tab

---

apps/server/migrations/20230809162826_add_agentId_to_requests.ts
packages/core/server/src/services/requests/requests.schema.ts
packages/core/shared/src/functions/saveRequest.ts
packages/core/shared/src/types.ts
packages/plugins/anthropic/server/src/functions/makeChatCompletion.ts
packages/plugins/database/server/src/functions/delete.ts
packages/plugins/database/server/src/functions/insert.ts
packages/plugins/database/server/src/functions/select.ts
packages/plugins/database/server/src/functions/update.ts
packages/plugins/database/server/src/functions/upsert.ts
packages/plugins/googleai/server/src/functions/makeChatCompletion.ts
packages/plugins/googleai/server/src/functions/makeTextCompletion.ts
packages/plugins/googleai/server/src/functions/makeTextEmbedding.ts
packages/plugins/localmodel/server/src/functions/makeChatCompletion.ts
packages/plugins/localmodel/server/src/functions/makeTextCompletion.ts
packages/plugins/localmodel/server/src/functions/makeTextEmbedding.ts
packages/plugins/openai/server/src/functions/makeChatCompletion.ts
packages/plugins/openai/server/src/functions/makeTextCompletion.ts
packages/plugins/openai/server/src/functions/makeTextEmbedding.ts
packages/plugins/openai/server/src/functions/makeTypeChatCompletion.ts

added agent id to request for agent analytics to work

---

packages/core/client/src/components/Drawer/Newsidebar/index.tsx
packages/editor/src/components/TabBar/TabBar.tsx
packages/editor/src/state/tabs.ts

Added IDs to component tabs like Events, Requests 
Open many tabs including windows like Events, Requests and try closing any of them accordingly 
[Screencast from 09.08.2023 10:39:38.webm](https://github.com/Oneirocom/Magick/assets/55635977/5443c207-9e04-4c6b-a2a6-9ff3d5a9f561)

Fix tab closing

---

packages/plugins/search/shared/src/functions/SearchMetaphor.ts

fixed missing argment in new plugin search metaphors

---

packages/agents/src/lib/Agent.ts

Just destructured the job data object in a different place.
the agent class is in dire need of some cleanup
make a spell with a generate text node and observe that the agent always responds to your messages on discord

fixes occasional missing secret which causes agents to be flakey

---

packages/core/server/src/services/documents/documents.class.ts

Documents hotfix

---

packages/editor/src/components/Node/Node.module.css
packages/editor/src/components/Node/Node.tsx

Changed socket text size and added 2 seconds delay for the tooltip text to appear 
Open any spell and try to view it's sockets

changing Tooltips css

---

packages/editor/src/windows/TextEditorWindow/index.tsx

Reverts Oneirocom/Magick#1230
Seems like this PR breaks autosaving and makes working with the text editor hard.
Reverting for now

Revert "Adding Auto-save in Text Editor "

---

packages/plugins/openai/shared/src/index.ts

Adds gpt-4 model to typechat
use typechat node with gpt-4

add gpt-4 to typechat

---

packages/cloud-agent-manager/src/lib/CloudAgentManager.ts

Adds back call for cloud agent manager startup

adds fix for agent startup on cold start

---

packages/core/client/src/components/Drawer/OldSidebar/index.tsx
packages/core/shared/src/engine.ts
packages/core/shared/src/nodes/document/GetDocuments.ts
packages/core/shared/src/nodes/document/StoreDocument.ts
packages/editor/src/screens/DocumentWindow/DocumentModal.tsx
packages/editor/src/screens/DocumentWindow/DocumentTable.tsx

Reverted the naming of document to knowledge

Changing the name of the document nodes broke spells in production. Hotfix to revert it.

---

packages/core/server/src/services/agentImage/agentImage.class.ts
packages/core/server/src/services/agentImage/agentImage.ts

Added in some missing services

Adds missing services

---

packages/editor/src/screens/Magick/magick.module.css
packages/editor/src/windows/PlaytestWindow.tsx

re-added line breaks to playtest window

---

packages/core/server/src/services/events/events.class.ts

- Bug fixes
- Create spell with event recall node
- Try spell in plates window

fixed event recall bug

---

.env
packages/config/src/config.ts
packages/plugins/rest/server/src/services/api/api.class.ts
packages/plugins/rest/server/src/services/api/api.schema.ts

implements a key to bypass rest agents normal checks.

cloud bypass

---

packages/core/client/src/components/Drawer/AgentMenu.tsx
packages/core/client/src/components/Drawer/OldSidebar/index.tsx

Fires iframe event to enable a back button in production.

fires iframe event in cloud for the back button

---

packages/core/server/src/services/spells/spells.ts
packages/core/shared/src/plugins/taskPlugin/task.ts

Fixes filer on back-propagating code in task plugin 
Graphs now run with variables as inputs to nodes.

Fix back propagation

---

packages/core/server/src/services/spells/spells.ts
packages/core/shared/src/spellManager/SpellManager.ts

We now attempt to load a spell if we can't find one when updating.

fixes spell loading and a linting error

---

packages/core/client/src/components/Drawer/AgentMenu.tsx
packages/core/client/src/contexts/TreeDataProvider.tsx
packages/editor/src/screens/agents/AgentManagerWindow.tsx
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx

I added state with will be shared on both components when ever there is any change to agents
Create agent on agent window and check well if newly created agent appears on agent dropdown
this will work when agent is also deleted or renamed

Agent Dropdown Update

---

packages/core/shared/src/nodes/boolean/IsVariableTrue.ts
packages/core/shared/src/nodes/boolean/LogicalOperator.ts
packages/core/shared/src/nodes/code/Javascript.ts
packages/core/shared/src/nodes/code/Python.ts
packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts
packages/core/shared/src/nodes/flow/BooleanGate.ts
packages/core/shared/src/nodes/flow/IsNullOrUndefined.ts
packages/core/shared/src/nodes/flow/RandomGate.ts
packages/core/shared/src/nodes/flow/SwitchGate.ts
packages/core/shared/src/nodes/io/Input.ts
packages/core/shared/src/nodes/number/Equal.ts
packages/core/shared/src/nodes/number/GreaterThan.ts
packages/core/shared/src/nodes/number/GreaterThanOrEqual.ts
packages/core/shared/src/nodes/number/InRange.ts
packages/core/shared/src/nodes/number/IsANumber.ts
packages/core/shared/src/nodes/number/LessThan.ts
packages/core/shared/src/nodes/number/LessThanOrEqual.ts
packages/core/shared/src/nodes/text/ComplexStringMatcher.ts
packages/core/shared/src/nodes/text/EvaluateText.ts
packages/core/shared/src/nodes/text/ProfanityFilter.ts
packages/core/shared/src/plugins/taskPlugin/index.ts
packages/core/shared/src/types.ts
packages/plugins/ethereum/shared/src/nodes/CheckForRecentTxFromWallet.ts
packages/plugins/ethereum/shared/src/nodes/CompileContract.ts
packages/plugins/ethereum/shared/src/nodes/DeployContract.ts
packages/plugins/ethereum/shared/src/nodes/GetERC20BalanceFromWallet.ts
packages/plugins/ethereum/shared/src/nodes/GetNativeBalanceFromWallet.ts
packages/plugins/ethereum/shared/src/nodes/GetRecentTxsFromWallet.ts

Fixes issue with broken socket closing which broke all flow nodes.
All flow nodes should work. WaitForAll, isStringTrue, Boolean Gate, etc.

Closed socket fix

---

packages/core/client/src/components/Drawer/AgentMenu.tsx
packages/core/client/src/components/Drawer/Newsidebar/index.tsx
packages/editor/src/screens/agents/AgentManagerWindow.tsx
packages/editor/src/screens/agents/AgentWindow/AgentItem.tsx

Default created agents are  not deletable  and when you rename an agent in agent menu it will immediately reflect on agent window
1. Create new project with no spell or agent 
2. create new spell in that project 
3. default agent will be created when you open that spell
4. perform different operations on that default created agent

Agent default value integration

---

packages/plugins/rest/server/src/services/agentHttp/agentHttp.class.ts

Fixes missing variables from query destructure

destructure isCloud from params.query

---

packages/core/server/src/metering/meters.ts

fix botched type

---

packages/core/client/src/templates/spells/Blank.spell.json
packages/core/client/src/templates/spells/Starter.spell.json

Update spell templates

---

packages/core/client/src/components/Drawer/AgentMenu.tsx
packages/core/client/src/components/Drawer/CustomNode.tsx
packages/core/client/src/components/Drawer/menu.module.css
packages/editor/src/screens/DocumentWindow/DocContentModal.tsx

- Disabled deleting agent when is the remaining agent in the current project
- Active tab indication in the file drawer
https://github.com/Oneirocom/Magick/assets/58092199/d34d4dd9-1935-4bdf-997f-fc35045c861e

added an indicator on selected file in file drawer

---

packages/plugins/rest/client/src/templates/spells/REST API.spell.json

- REST API spell template 
- Create a new spell using the REST API template
- Make the spell a root spell for your agent, then chat with your agent

REST API spell template

---

packages/core/shared/src/spellManager/SpellRunner.ts

Input fallbacks

---

apps/client/src/globals.css
apps/client/tailwind.config.js

Fixes the tailwind css glitches. had to: disable preflight plugin and remove conflicting color

set tailwind preflight to false

---

packages/agents/src/lib/Agent.ts
packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts
packages/config/src/config.ts
packages/core/server/src/app.ts
packages/core/server/src/hooks/authenticateApiKey.ts
packages/plugins/rest/server/src/services/agentHttp/agentHttp.ts

Adds API key auth to the server.  It bypasses all authentication if present.  Allows the cloud server to talk directly to our server API.  This was added to the cloud server can update agents via the server API which triggers off feathers update events to update agents with changed public variables.
Everything should work as normal.  Cloud agent chat page should be able to set public variables and trigger off the cloud agent worker to notice the changes and update the live agent.

Api token auth

---

packages/editor/src/screens/DocumentWindow/DocumentModal.tsx

fix multiple uploads

---

packages/core/client/src/components/Drawer/CustomNode.tsx

Fix rename spell error 

---

package-lock.json
packages/agents/src/lib/AgentCommander.ts
packages/core/shared/src/nodes/io/SpellByName.ts
packages/core/shared/src/spellManager/SpellRunner.ts
packages/editor/src/screens/agents/AgentWindow/AgentDetails.tsx
packages/plugins/bluesky/server/src/connectors/bluesky.ts
packages/plugins/discord/server/src/connectors/discord-voice.ts
packages/plugins/discord/server/src/connectors/discord.ts
packages/plugins/discord/shared/src/nodes/utils.ts
packages/plugins/github/server/src/connectors/github.ts
packages/plugins/loop/server/src/index.ts
packages/plugins/rest/server/src/services/agentHttp/agentHttp.class.ts
packages/plugins/task/server/src/index.ts
packages/plugins/twitter/server/src/connectors/twitter.ts

Fixes issue with how discord spell is called after having runSpell in commander not require a full agent to run but just an agentId.

Discord agent fix

---

apps/client/src/main.tsx

Makes trusted origins an array.

Make trusted origins an array

---

packages/core/shared/src/nodes/text/GenerateText.ts

Quick null check to fix error in prod

customModel length hotfix

---

packages/plugins/openai/server/src/functions/makeChatCompletion.ts

HOTFIX- length fix

---

packages/core/server/src/services/documents/documents.class.ts

doc hotfix

---

packages/core/server/src/services/events/events.class.ts
packages/core/shared/src/nodes/events/EventRecall.ts
packages/core/shared/src/types.ts

More small fixes to event filtering

Make project id hard coded for events. Fix filters more.

---

apps/client/src/main.tsx
packages/client/providers/src/lib/ConfigProvider.tsx

Unify posthog

---

packages/plugins/intent/client/src/windows/IntentWindow/IntentTable.tsx
packages/server/core/src/services/documents/documents.class.ts

- fix intent creation
- fix document creation using the document node

Jeeves fixes

---

packages/server/core/src/services/events/events.class.ts
packages/shared/core/src/nodes/audio/TextToSpeech.ts
packages/shared/core/src/nodes/events/EventRecall.ts
packages/shared/core/src/nodes/events/EventStore.ts
packages/shared/core/src/types.ts

Prod merge

---

packages/server/cloud-agent-manager/src/lib/CloudAgentManager.ts
packages/server/cloud-agent-worker/src/lib/cloud-agent-worker.ts

fix knex adaptor type issues

---

apps/server/migrations/20231215080811_update_coversation_to_conversation.ts

I updated the coversation_id to conversation to fix storing the chat history prompts and response.

Update coversation_id to conversationId

---

packages/server/core/src/services/spells/spells.class.ts

Fixes bug with saveDiff due to spellRelease changes
Make a change to a spell (drag a node)

fix saveDiff to handle releases

---

apps/server/migrations/20231218220320_changeChatHistoryToTextFromVarchar.ts

fixes an issue with chat messages that are too long

changes chatMessage string to text

---

packages/plugins/googleai/server/src/constants.ts
packages/plugins/googleai/server/src/functions/makeChatCompletion.ts
packages/plugins/googleai/shared/src/index.ts
packages/plugins/openai/shared/src/index.ts

Adds support for gemin-pro and gpt-4-1106.
Gemini is a little different. Since it's a multimodal model, it generates "content" even when using the version that only generates text.

adds geminni-pro and gpt-4-1106

---

.husky/post-merge
.husky/pre-commit
.husky/pre-push
package-lock.json
package.json

Husky hooks

---

packages/shared/nodeSpec/src/credentials.json
packages/shared/nodeSpec/src/nodeSpec.json
plugins/core/src/lib/corePlugin.ts
plugins/core/src/lib/nodes/actions/generateText.ts
plugins/core/src/lib/nodes/billing/budgetManager.ts
plugins/core/src/lib/services/coreBudgetManagerService/coreBudgetMangerService.ts
plugins/core/src/lib/services/coreLLMService/coreLLMService.ts
plugins/core/src/lib/services/coreLLMService/types.ts
plugins/core/tsconfig.lib.json
poetry.lock
pyproject.toml

Budget manager 2
